config/routes.rb
Rails.application.routes.draw do
  root 'quizzes#home'
  get 'quizzes/start' => 'quizzes#start'
  get 'quizzes/end' => 'quizzes#end'
  post "quizzes/answer"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/indication.rb
class Indication < ActiveRecord::Base
end

app/models/solution.rb
class Solution < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def home
    session[:number] = 3
  end

  def start
    puts session[:number]
    if session[:number] == 3
      @indication = Indication.first(session[:number])
    elsif session[:number] == 4
      @indication = Indication.where(code: ['p04', 'p06'])
    elsif session[:number] == 5
      @indication = Indication.where(code: ['p05'])

    elsif session[:number] == 7
      @indication = Indication.where(code: ['p08', 'p10'])
    elsif session[:number] == 8
      @indication = Indication.where(code: ['p09'])
    elsif session[:number] == 10
      @indication = Indication.where(code: ['p07'])
    elsif session[:number] == 12
      @indication = Indication.where(code: ['p11'])
    elsif session[:number] == 14
      @indication = Indication.where(code: ['p12', 'p14'])
    elsif session[:number] == 15
      @indication = Indication.where(code: ['p13'])
    elsif session[:number] == 17
      @indication = Indication.where(code: ['p15'])
    end
  end

  def answer
    if params[:indication] == 'P01'
      session[:number] = 4
      redirect_to action: "start"
    elsif params[:indication] == 'P04'
      session[:number] = 5
      redirect_to action: "start"
    elsif params[:indication] == 'P05'
      session[:number] = 6
      redirect_to action: "end"


    elsif params[:indication] == 'P02'
      session[:number] = 7
      redirect_to action: "start"
    elsif params[:indication] == 'P08'
      session[:number] = 8
      redirect_to action: "start"
    elsif params[:indication] == 'P09'
      session[:number] = 9
      redirect_to action: "end"

    elsif params[:indication] == 'P06'
      session[:number] = 10
      redirect_to action: "start"
    elsif params[:indication] == 'P07'
      session[:number] = 11
      redirect_to action: "end"

    elsif params[:indication] == 'P10'
      session[:number] = 12
      redirect_to action: "start"
    elsif params[:indication] == 'P11'
      session[:number] = 13
      redirect_to action: "end"

    elsif params[:indication] == 'P03'
      session[:number] = 14
      redirect_to action: "start"
    elsif params[:indication] == 'P12'
      session[:number] = 15
      redirect_to action: "start"
    elsif params[:indication] == 'P13'
      session[:number] = 16
      redirect_to action: "end"

    elsif params[:indication] == 'P14'
      session[:number] = 17
      redirect_to action: "start"
    elsif params[:indication] == 'P15'
      session[:number] = 18
      redirect_to action: "end"
    else
      #code
    end
  end

  def end
    if session[:number] == 6
      @solution = Solution.find_by_code('s01')
    elsif session[:number] == 9
      @solution = Solution.find_by_code('s03')
    elsif session[:number] == 11
      @solution = Solution.find_by_code('s02')
    elsif session[:number] == 13
      @solution = Solution.find_by_code('s04')
    elsif session[:number] == 16
      @solution = Solution.find_by_code('s05')
    elsif session[:number] == 18
      @solution = Solution.find_by_code('s06')
    end
    @solution = Solution.find_by_code('s01')
    session[:number] = 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpertSystem</title>
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script type="text/javascript">
  $(function(){
    var loading = $('#loadbar').hide();
    $(document)
    .ajaxStart(function () {
        loading.show();
    }).ajaxStop(function () {
      loading.hide();
    });
    
    $("label.btn").on('click',function () {
      var choice = $(this).find('input:radio').val();
      $('#loadbar').show();
      $('#quiz').fadeOut();

      setTimeout(function(){
           $( "#answer" ).html(  $(this).checking(choice) );      
            $('#quiz').show();
            $('#loadbar').fadeOut();
           /* something else */
            $.ajax({
              data: {
                indication: choice,
              },
              type: "POST",
              url: "/quizzes/answer",
              success: function (data) {
                //$('#loadbar').hide();
              }
            });
          }, 1500);
    });

    $ans = 3;

    $.fn.checking = function(ck) {
        if (ck != $ans)
            return 'INCORRECT';
        else 
            return 'CORRECT';
    }; 
}); 

</script>
</body>
</html>

app/views/quizzes/answer.html.erb
<%# controller.redirect_to quizzes_start_path %>

app/views/quizzes/end.html.erb
<%= image_tag("solution1", class: "center-block") %>
<h1 align="center"><%= @solution.name %></h1> <br />
<%= link_to "Back to start", root_path, class: "btn btn-lg btn-block" %>

app/views/quizzes/home.html.erb
<%= image_tag("printer2", class: "center-block") %>

<h1 align="center">Welcome to service printer</h1>
<%= link_to "Start To Diagnose", quizzes_start_path, class: "center-link" %>

app/views/quizzes/start.html.erb
<div class="container-fluid">
    <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h3><span class="label label-warning" id="qid">1</span> Please Select Your Problem</h3>
        </div>
        <div class="modal-body">
            <div class="col-xs-3 col-xs-offset-5">
               <div id="loadbar" style="display: none;">
                  <div class="blockG" id="rotateG_01"></div>
                  <div class="blockG" id="rotateG_02"></div>
                  <div class="blockG" id="rotateG_03"></div>
                  <div class="blockG" id="rotateG_04"></div>
                  <div class="blockG" id="rotateG_05"></div>
                  <div class="blockG" id="rotateG_06"></div>
                  <div class="blockG" id="rotateG_07"></div>
                  <div class="blockG" id="rotateG_08"></div>
              </div>
          </div>

          <div class="quiz" id="quiz" data-toggle="buttons">
            <% @indication.each_with_index do |ind, index| %>
            <% index += 1 %>
            <label class="element-animation<%= index %> btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> 
            <%= radio_button_tag :name, ind.code %><%= ind.name %></label>
            <% end %>
       </div>
   </div>
   <div class="modal-footer text-muted">
    <span id="answer"></span>
</div>
</div>
</div>
</div>